"""Daily stock analysis pipeline runner — auto-generated by Hermes cron."""
import os
import sys

# Load .env
env_path = os.path.join(os.path.dirname(__file__), '.env')
with open(env_path) as f:
    for line in f:
        if line.strip() and not line.startswith('#') and '=' in line:
            k, v = line.strip().split('=', 1)
            os.environ[k] = v

sys.path.insert(0, os.path.dirname(__file__))

from backend.pipeline import analyze_ticker

WATCHLIST = ['AAPL', 'MSFT', 'NVDA', 'GOOGL', 'META', 'ASML', 'MC.PA']

results = {}
errors = {}

for t in WATCHLIST:
    try:
        r = analyze_ticker(t, output_base='analyses')
        results[t] = (r.decision, r.scoring.total, getattr(r, 'conviction', 'N/A'))
        print(f'{t}: {r.decision} {r.scoring.total}/40')
    except Exception as e:
        errors[t] = str(e)
        print(f'{t}: ERROR {e}')

print("\n---SUMMARY---")
print("TICKER|DECISION|SCORE|CONVICTION")
for t, (dec, score, conv) in results.items():
    print(f"{t}|{dec}|{score}/40|{conv}")

if errors:
    print("\n---ERRORS---")
    for t, e in errors.items():
        print(f"{t}: {e}")
else:
    print("\nNo errors.")
