"""Daily backlog runner — auto-generated by Hermes cron job."""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Load .env
with open('.env') as f:
    for line in f:
        if line.strip() and not line.startswith('#') and '=' in line:
            k, v = line.strip().split('=', 1)
            os.environ[k] = v

from backend.pipeline import analyze_ticker

TICKERS = ['AAPL', 'MSFT', 'NVDA', 'GOOGL', 'META', 'ASML', 'MC.PA']
results = []

for t in TICKERS:
    try:
        r = analyze_ticker(t, output_base='analyses')
        result_line = f"{t}: {r.decision} {r.scoring.total}/40 (conviction: {r.scoring.conviction})"
        print(result_line)
        results.append(result_line)
    except Exception as e:
        err_line = f"{t}: ERROR — {e}"
        print(err_line)
        results.append(err_line)

print("\n--- SUMMARY COMPLETE ---")
for r in results:
    print(r)
