"""Run MC.PA ticker — auto-generated by Hermes cron."""
import os
import sys

env_path = os.path.join(os.path.dirname(__file__), '.env')
with open(env_path) as f:
    for line in f:
        if line.strip() and not line.startswith('#') and '=' in line:
            k, v = line.strip().split('=', 1)
            os.environ[k] = v

sys.path.insert(0, os.path.dirname(__file__))

from backend.pipeline import analyze_ticker

try:
    r = analyze_ticker('MC.PA', output_base='analyses')
    conv = getattr(r, 'conviction', 'N/A')
    print(f'MC.PA: {r.decision} {r.scoring.total}/40 conviction={conv}')
except Exception as e:
    print(f'MC.PA: ERROR {e}')
