"""Backend i18n — label translations for API responses and documents."""

TRANSLATIONS = {
    "en": {
        # Decisions
        "BUY": "BUY",
        "HOLD / BUY ON PULLBACK": "HOLD / BUY ON PULLBACK",
        "HOLD fragile": "HOLD fragile",
        "SELL or AVOID": "SELL or AVOID",
        # Conviction
        "High": "High",
        "Moderate": "Moderate",
        "Low": "Low",
        "conviction": "conviction",
        # Insights
        "🚀 Strong momentum detected": "🚀 Strong momentum detected",
        "📈 Undervalued vs sector": "📈 Undervalued vs sector",
        "🏛️ Stable fundamentals": "🏛️ Stable fundamentals",
        "🛡️ Strong competitive moat": "🛡️ Strong competitive moat",
        "👔 Quality management signals": "👔 Quality management signals",
        "📊 Consistent growth pattern": "📊 Consistent growth pattern",
        "⚠️ Valuation concerns": "⚠️ Valuation concerns",
        "🌍 Geopolitical exposure flagged": "🌍 Geopolitical exposure flagged",
        "🔍 Mixed signals — review full report": "🔍 Mixed signals — review full report",
        # Scoring
        "Growth": "Growth",
        "Profitability": "Profitability",
        "Financial Strength": "Financial Strength",
        "Moat": "Moat",
        "Management": "Management",
        "Valuation Risk": "Valuation Risk",
        "Geopolitical Risk": "Geopolitical Risk",
        "Business Momentum": "Business Momentum",
        "Composite Score": "Composite Score",
        # Dossier
        "Stock Analysis Dossier": "Stock Analysis Dossier",
        "Generated by Stock Analysis Pipeline": "Generated by Stock Analysis Pipeline",
        "Disclaimer": "This is an automated research tool, not financial advice.",
    },
    "jp": {
        # Decisions
        "BUY": "買い",
        "HOLD / BUY ON PULLBACK": "ホールド / 押し目買い",
        "HOLD fragile": "ホールド (弱気)",
        "SELL or AVOID": "売り / 回避",
        # Conviction
        "High": "高い",
        "Moderate": "中程度",
        "Low": "低い",
        "conviction": "確信度",
        # Insights
        "🚀 Strong momentum detected": "🚀 強いモメンタム検出",
        "📈 Undervalued vs sector": "📈 セクター比で割安",
        "🏛️ Stable fundamentals": "🏛️ 安定したファンダメンタルズ",
        "🛡️ Strong competitive moat": "🛡️ 強い競争優位性",
        "👔 Quality management signals": "👔 質の高い経営陣のシグナル",
        "📊 Consistent growth pattern": "📊 一貫した成長パターン",
        "⚠️ Valuation concerns": "⚠️ バリュエーション懸念",
        "🌍 Geopolitical exposure flagged": "🌍 地政学的リスクあり",
        "🔍 Mixed signals — review full report": "🔍 混在シグナル — 詳細レポートを確認",
        # Scoring
        "Growth": "成長性",
        "Profitability": "収益性",
        "Financial Strength": "財務力",
        "Moat": "競争優位性",
        "Management": "経営陣",
        "Valuation Risk": "バリュエーションリスク",
        "Geopolitical Risk": "地政学リスク",
        "Business Momentum": "事業モメンタム",
        "Composite Score": "総合スコア",
        # Dossier
        "Stock Analysis Dossier": "株式分析ドシエ",
        "Generated by Stock Analysis Pipeline": "Stock Analysis Pipeline により生成",
        "Disclaimer": "これは自動調査ツールであり、投資助言ではありません。",
        # PDF labels — earnings deep-dive
        "Earnings Deep-Dive": "決算詳細分析",
        "Official Website": "公式ウェブサイト",
        "Sources": "ソース",
        "Key Dates": "主要日程",
        "Earnings Documents": "決算資料",
        "Data & Analytics": "データ & アナリティクス",
        "Claim Traceability": "主張の追跡可能性",
        "Source Legend": "ソース凡例",
        "Claims by Section": "セクション別主張",
        "Methodology": "手法",
        "Document / Source": "ドキュメント / ソース",
        "Target-company URL or status": "企業URLまたはステータス",
        "Used for": "用途",
        "… and {n} more claims (see machine-readable export)": "… 他{n}件の主張（機械可読エクスポートを参照）",
        # Long-form text blocks
        "This deep-dive combines quantitative metrics from SEC filings "
        "(via yfinance/Finnhub) with qualitative analysis of the earnings call transcript. "
        "All figures are sourced; no data is invented. "
        "Ratings reflect Nami-grade buy-side analysis standards.":
            "この詳細分析は、SEC提出書類（yfinance/Finnhub経由）の定量指標と"
            "決算説明会トランスクリプトの定性分析を組み合わせています。"
            "すべての数値はソースに基づき、捏造データはありません。"
            "格付けはNami基準のバイサイド分析水準を反映しています。",
        "Every analytical claim in this report is traceable to a specific data source. "
        "This appendix provides the audit trail.":
            "このレポートのすべての分析的主張は特定のデータソースに遡ることができます。"
            "この付録は監査証跡を提供します。",
        "Grounding levels:":
            "裏付けレベル：",
        "direct_metric = exact source value | "
        "calculated = formula from source data | direct_quote = transcript | "
        "document_fact = filing fact | inference = analyst interpretation | "
        "unsupported = blocked":
            "direct_metric = ソース値そのまま | "
            "calculated = ソースデータからの計算式 | direct_quote = トランスクリプト引用 | "
            "document_fact = 提出書類の事実 | inference = アナリスト解釈 | "
            "unsupported = ブロック",
        # Company Overview labels
        "Company Overview": "会社概要",
        "Business Description": "事業概要",
        "Key Financials": "主要財務指標",
        "Competitive Position": "競争ポジション",
        "Recent Developments": "最近の動向",
        "Competitors": "競合他社",
        "Employees": "従業員数",
        "Headquarters": "本社所在地",
        "Sector": "セクター",
        "Industry": "業界",
        "Founded": "設立",
        "Website": "ウェブサイト",
        "Ticker": "ティッカー",
        "Market Cap": "時価総額",
        "Revenue": "売上高",
        "P/E Ratio": "PER（株価収益率）",
        "Forward P/E": "予想PER",
        "Dividend Yield": "配当利回り",
        "Beta": "ベータ",
        "52-Week Range": "52週レンジ",
        "Competitor": "競合",
        "Comparison": "比較",
        "Advantage": "優位性",
    },
}


def translate(value: str, lang: str = "en") -> str:
    """Translate a label to the target language. Falls back to English."""
    if lang in ("en", ""):
        return value
    # TRANSLATIONS key normalized to "jp"
    t = TRANSLATIONS.get(lang, {})
    return t.get(value, value)  # Return original if no translation found


def translate_dict(data: dict, lang: str, keys: list[str] | None = None) -> dict:
    """Translate specific keys in a dict in-place."""
    if lang == "en":
        return data
    target_keys = keys or []
    for key in target_keys:
        if key in data and isinstance(data[key], str):
            data[key] = translate(data[key], lang)
    return data
