"""Backend i18n — label translations for API responses and documents."""

TRANSLATIONS = {
    "en": {
        # Decisions
        "BUY": "BUY",
        "HOLD / BUY ON PULLBACK": "HOLD / BUY ON PULLBACK",
        "HOLD fragile": "HOLD fragile",
        "SELL or AVOID": "SELL or AVOID",
        # Conviction
        "High": "High",
        "Moderate": "Moderate",
        "Low": "Low",
        "conviction": "conviction",
        # Insights
        "🚀 Strong momentum detected": "🚀 Strong momentum detected",
        "📈 Undervalued vs sector": "📈 Undervalued vs sector",
        "🏛️ Stable fundamentals": "🏛️ Stable fundamentals",
        "🛡️ Strong competitive moat": "🛡️ Strong competitive moat",
        "👔 Quality management signals": "👔 Quality management signals",
        "📊 Consistent growth pattern": "📊 Consistent growth pattern",
        "⚠️ Valuation concerns": "⚠️ Valuation concerns",
        "🌍 Geopolitical exposure flagged": "🌍 Geopolitical exposure flagged",
        "🔍 Mixed signals — review full report": "🔍 Mixed signals — review full report",
        # Scoring
        "Growth": "Growth",
        "Profitability": "Profitability",
        "Financial Strength": "Financial Strength",
        "Moat": "Moat",
        "Management": "Management",
        "Valuation Risk": "Valuation Risk",
        "Geopolitical Risk": "Geopolitical Risk",
        "Business Momentum": "Business Momentum",
        "Composite Score": "Composite Score",
        # Dossier
        "Stock Analysis Dossier": "Stock Analysis Dossier",
        "Generated by Stock Analysis Pipeline": "Generated by Stock Analysis Pipeline",
        "Disclaimer": "This is an automated research tool, not financial advice.",
    },
    "ja": {
        # Decisions
        "BUY": "買い",
        "HOLD / BUY ON PULLBACK": "ホールド / 押し目買い",
        "HOLD fragile": "ホールド (弱気)",
        "SELL or AVOID": "売り / 回避",
        # Conviction
        "High": "高い",
        "Moderate": "中程度",
        "Low": "低い",
        "conviction": "確信度",
        # Insights
        "🚀 Strong momentum detected": "🚀 強いモメンタム検出",
        "📈 Undervalued vs sector": "📈 セクター比で割安",
        "🏛️ Stable fundamentals": "🏛️ 安定したファンダメンタルズ",
        "🛡️ Strong competitive moat": "🛡️ 強い競争優位性",
        "👔 Quality management signals": "👔 質の高い経営陣のシグナル",
        "📊 Consistent growth pattern": "📊 一貫した成長パターン",
        "⚠️ Valuation concerns": "⚠️ バリュエーション懸念",
        "🌍 Geopolitical exposure flagged": "🌍 地政学的リスクあり",
        "🔍 Mixed signals — review full report": "🔍 混在シグナル — 詳細レポートを確認",
        # Scoring
        "Growth": "成長性",
        "Profitability": "収益性",
        "Financial Strength": "財務力",
        "Moat": "競争優位性",
        "Management": "経営陣",
        "Valuation Risk": "バリュエーションリスク",
        "Geopolitical Risk": "地政学リスク",
        "Business Momentum": "事業モメンタム",
        "Composite Score": "総合スコア",
        # Dossier
        "Stock Analysis Dossier": "株式分析ドシエ",
        "Generated by Stock Analysis Pipeline": "Stock Analysis Pipeline により生成",
        "Disclaimer": "これは自動調査ツールであり、投資助言ではありません。",
    },
}


def translate(value: str, lang: str = "en") -> str:
    """Translate a label to the target language. Falls back to English."""
    if lang == "en":
        return value
    t = TRANSLATIONS.get(lang, {})
    return t.get(value, value)  # Return original if no translation found


def translate_dict(data: dict, lang: str, keys: list[str] | None = None) -> dict:
    """Translate specific keys in a dict in-place."""
    if lang == "en":
        return data
    target_keys = keys or []
    for key in target_keys:
        if key in data and isinstance(data[key], str):
            data[key] = translate(data[key], lang)
    return data
