"""
Live NVDA smoke test — uses real external data. Manual/nightly only.
Validates that the live pipeline still works with actual market data.
Not for pre-commit — too slow and depends on external APIs.
"""
import pytest
import sys
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT))

pytestmark = [pytest.mark.slow, pytest.mark.live]


@pytest.fixture(scope="module")
def nvda_live():
    """Run full pipeline on NVDA with live data. Module-scoped."""
    from backend.pipeline import analyze_ticker_fast
    return analyze_ticker_fast("NVDA", output_base=str(PROJECT / "tests" / "tmp"))


class TestLiveNVDA:
    """Live pipeline — validates real API integration."""

    def test_live_pipeline_does_not_crash(self, nvda_live):
        assert nvda_live is not None
        assert nvda_live.ticker == "NVDA"

    def test_live_score_in_range(self, nvda_live):
        # AnalysisResult.score was replaced by the 6-category Scoring model
        total = nvda_live.scoring.total
        assert 0 <= total <= 40, f"Score {total} out of range"

    def test_live_pdf_generated(self, nvda_live):
        """The fast path writes <output_base>/<ts>_NVDA_*/07_final_report/report.pdf
        (the light analysis report — the deep-dive PDF is generated by the
        background dossier, out of scope for this smoke)."""
        import glob
        pdf_path = getattr(nvda_live, 'pdf_path', None)
        if pdf_path is None:
            candidates = sorted(
                glob.glob(str(PROJECT / "tests" / "tmp" / "*_NVDA_*" / "07_final_report" / "report.pdf"))
            )
            pdf_path = candidates[-1] if candidates else None
        assert pdf_path and Path(pdf_path).exists(), "No PDF"
        # Light report.pdf is ~7KB; guard against an empty/corrupted artifact
        assert Path(pdf_path).stat().st_size > 3000

    def test_live_decision_maps_to_score(self, nvda_live):
        score = nvda_live.scoring.total
        decision = nvda_live.decision.upper()
        if score >= 28:
            assert decision == "BUY"
        elif score >= 15:
            assert decision == "HOLD"
        else:
            assert decision == "SELL"

    def test_live_data_contract(self, nvda_live):
        """pre_render_validator rejects on live data."""
        if hasattr(nvda_live, 'deep_dive') and nvda_live.deep_dive:
            dd = nvda_live.deep_dive
            if dd:
                assert dd.report is not None
                sections = getattr(dd.report, 'sections', {})
                required = ['summary', 'financial_highlights', 'valuation', 
                          'growth_outlook', 'risks', 'verdict']
                for section in required:
                    assert section in sections, f"Missing section: {section}"
